spring.datasource.url=jdbc:postgresql://localhost:5432/cargohub
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Entorno local estable para preservar esquema y datos entre reinicios
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
